services:
  postgres-db:
    image: postgres:18-alpine
    container_name: postgres-db-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kanjiya
      POSTGRES_USER: root
      POSTGRES_PASSWORD: s3cret
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
