spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: kanjiya
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default-schema: public
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:false}
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: public